#install.packages("rstudioapi")
library(rstudioapi)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
df <- read.csv(file = "Group_Assignment_3_Dataset.txt", header = TRUE)
#install.packages("ggcorrplot")
#install.packages("gglot2")
library(ggplot2)
library(ggcorrplot)
#install.packages("data.table")
library(data.table)
#install.packages("hms")
library(hms)
#install.packages("dplyr")
library(dplyr)
#install.packages("depmixS4")
library(depmixS4)
df$Date <- as.POSIXlt(df$Date,format = "%d/%m/%Y")
df$Time <- as.POSIXlt(df$Time,format = "%H:%M:%S")
# We choose Monday 09:00 - 11:00
df <- subset(df, df$Time$hour >= 9 & df$Time$hour < 11)
df <- subset(df, df$Date$wday == 1)
# We choose Global_active_power
df$Global_active_power <- scale(df$Global_active_power)
li <- rep(120,53)

set.seed(1)

mod1 <- depmix(response = Global_active_power~1, data = df, nstates = 3, ntimes = li)
fm1 <- fit(mod1)
mod2 <- depmix(response = Global_active_power~1, data = df, nstates = 7, ntimes = li)
fm2 <- fit(mod2)
mod3 <- depmix(response = Global_active_power~1, data = df, nstates = 11, ntimes = li)
fm3 <- fit(mod3)                           
mod4 <- depmix(response = Global_active_power~1, data = df, nstates = 16, ntimes = li)
fm4 <- fit(mod4)
print(fm3)
print(fm4)

plot(1:4,c(BIC(fm1),BIC(fm2),BIC(fm3),BIC(fm4)),ty="b")

 mod1 <- depmix(response = Global_active_power~1, data = df, nstates = 8, ntimes = li)
fm1 <- fit(mod1)
mod2 <- depmix(response = Global_active_power~1, data = df, nstates = 11, ntimes = li)
fm2 <- fit(mod2)
mod3 <- depmix(response = Global_active_power~1, data = df, nstates = 13, ntimes = li)
fm3 <- fit(mod3)  
print(fm3)
mod4 <- depmix(response = Global_active_power~1, data = df, nstates = 16, ntimes = li)
fm4 <- fit(mod4)
plot(1:4,c(BIC(fm1),BIC(fm2),BIC(fm3),BIC(fm4)),ty="b")
